#
# ppc64 makefile
#
# Authors: Andrew Jones <drjones@redhat.com>
#
bits = 64

arch_CFLAGS = -mbig-endian
arch_LDFLAGS = -EB

cstart.o = $(TEST_DIR)/cstart64.o
reloc.o  = $(TEST_DIR)/reloc64.o
cflatobjs += lib/ppc64/spinlock.o

# ppc64 specific tests
tests =

include $(TEST_DIR)/Makefile.common

arch_clean: powerpc_clean
	$(RM) lib/ppc64/.*.d
