#!/usr/bin/env bash

if [ -z "$STANDALONE" ]; then
	if [ ! -f config.mak ]; then
		echo "run ./configure && make first. See ./configure -h"
		exit 2
	fi
	source config.mak
	source scripts/arch-run.bash
fi

if [ -c /dev/kvm ]; then
	if [ "$HOST" = "s390x" ] && [ "$ARCH" = "s390x" ]; then
		kvm_available=yes
	fi
fi

if [ "$ACCEL" = "kvm" ] && [ "$kvm_available" != "yes" ]; then
	echo "KVM is needed, but not available on this host"
	exit 2
fi

if [ -z "$ACCEL" ]; then
	if [ "$kvm_available" = "yes" ]; then
		ACCEL="kvm"
	else
		ACCEL="tcg"
	fi
fi

qemu=$(search_qemu_binary) ||
	exit $?

M='-machine s390-ccw-virtio'
M+=",accel=$ACCEL"
command="$qemu -nodefaults -nographic $M"
command+=" -chardev stdio,id=con0 -device sclpconsole,chardev=con0"
command+=" -kernel"
command="$(timeout_cmd) $command"

# We return the exit code via stdout, not via the QEMU return code
run_qemu_status $command "$@"
