#ifndef _ASMX86_MEMORY_AREAS_H_
#define _ASMX86_MEMORY_AREAS_H_

#define AREA_NORMAL_PFN BIT(36-12)
#define AREA_NORMAL_NUMBER 0
#define AREA_NORMAL (1 << AREA_NORMAL_NUMBER)

#define AREA_HIGH_PFN BIT(32-12)
#define AREA_HIGH_NUMBER 1
#define AREA_HIGH (1 << AREA_HIGH_NUMBER)

#define AREA_LOW_PFN BIT(24-12)
#define AREA_LOW_NUMBER 2
#define AREA_LOW (1 << AREA_LOW_NUMBER)

#define AREA_LOWEST_PFN 0
#define AREA_LOWEST_NUMBER 3
#define AREA_LOWEST (1 << AREA_LOWEST_NUMBER)

#define MAX_AREAS 4

#define AREA_DMA24 AREA_LOWEST
#define AREA_DMA32 (AREA_LOWEST | AREA_LOW)
#define AREA_PAE36 (AREA_LOWEST | AREA_LOW | AREA_HIGH)

#endif
