cstart.o = $(TEST_DIR)/cstart.o
bits = 32
ldarch = elf32-i386

cflatobjs += lib/x86/setjmp32.o

tests = $(TEST_DIR)/taskswitch.flat $(TEST_DIR)/taskswitch2.flat \
	$(TEST_DIR)/cmpxchg8b.flat

include $(SRCDIR)/$(TEST_DIR)/Makefile.common
